language: go

go:
  - 1.7.1

env:
  global:
    - ORACLE_COOKIE=sqldev
    - ORACLE_FILE=oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
    - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
    - ORACLE_SID=XE
    - LD_LIBRARY_PATH=$ORACLE_HOME/lib

sudo: required

before_install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
  - sudo cp $HOME/gopath/src/github.com/dddpaul/regiond/.travis/oci8.pc /usr/lib/pkgconfig

before_script:
  # Makefile builds docker container and we don't need this in Travis CI
  - rm Makefile
