version: "2"

services:

  server1:
#    image: docker.infoline.ru:5000/smile/fedpa-proxy:1.0
    image: smile/fedpa-proxy:1.0
    ports: ["9091:80"]
    entrypoint: ["server", "80"]

  server2:
#    image: docker.infoline.ru:5000/smile/fedpa-proxy:1.0
    image: smile/fedpa-proxy:1.0
    ports: ["9092:80"]
    entrypoint: ["server", "80"]

  proxy:
#    image: docker.infoline.ru:5000/smile/fedpa-proxy:1.0
    image: smile/fedpa-proxy:1.0
    depends_on: ["server1", "server2"]
    ports: ["9090:80"]
    entrypoint: ["proxy"]
